name: 'Inspec Tools Action'
author: The MITRE Corporation
description: >
  Check summary and threshold with inspec Tools
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
inputs:
  thresholdfile:
    description: 'Inspec Tools threshold file which sets the min/max results allowed in each category'
    required: true
    deprecationMessage: 'THIS ACTION IS DEPRECATED. Use mitre/saf_action to replace this action. Find it here: https://github.com/mitre/saf_action'
  resultsfile:
    description: 'Inspec results in JSON format'
    required: true
    deprecationMessage: 'THIS ACTION IS DEPRECATED. Use mitre/saf_action to replace this action. Find it here: https://github.com/mitre/saf_action'
  command:
    description: 'Inspec Tools command to run'
    required: true
    deprecationMessage: 'THIS ACTION IS DEPRECATED. Use mitre/saf_action to replace this action. Find it here: https://github.com/mitre/saf_action'
runs:
  using: 'docker'
  image: 'Dockerfile'
