name: 'Inspec Tools Action'
author: The MITRE Corporation
description: >
  Check summary and threshold with inspec Tools
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
inputs:
  thresholdfile:
    description: 'Inspec Tools threshold file which sets the min/max results allowed in each category'
    required: true
  resultsfile:
    description: 'Inspec results in JSON format'
    required: true
  command:
    description: 'Inspec Tools command to run'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
